### ISSUE TITLE
cucumber doesn't show the executed steps

### ISSUE THREAD

**Issue by heuism** [mfrachet/detox-example#2]
Hi @mfrachet, thanks for helping out with the cucumber example.
However, I have the question about displaying the step. Not sure why eventhough it pass. It didn't show the step in the terminal

```
        tail -F $HOME/Library/Developer/CoreSimulator/Devices/47F630BB-0129-447A-AAA3-29B45114D902/data/tmp/detox.last_launch_app_log.{out,err} 
.........

1 scenario (1 passed)
7 steps (7 passed)
0m20.731s

```

The `.........` I guess was representing those steps but It doesn't look informative enough.

Can you help me with this? I am still quite new with cucumber.

Thanks

**Comment by heuism** [comment]
And I wonder when we run npm run cucumber. Would this still call detox to run? And what is cucumber roles in the test? Thanks

**Comment by seekasiacarrielai** [comment]
@heuism Since cucumber-JS 3.0, they decided to hide the executed steps if the test passed, but the steps will be shown if it failed

**Comment by mfrachet** [comment]
Aww, I've just seen the issue, sorry for being that late...

Well actually, cucumber is a test runner that allows to write based on a specific "feature like" language called gherkin. It only aims to create javascript code (test syntax) based on gherkin (humain syntax) and run the javascript, just like mocha / jest would have done it.

I wasn't aware of @seekasiacarrielai information, thank you for that :)

To answer the second question, cucumber is able to run detox thanks to the `hooks` file located here : https://github.com/mfrachet/detox-example/blob/cucumber/e2e/features/step_definitions/hooks.js

It's simply an init file that cucumber is aware of and that acts the same way `init.js` would have act for mocha. This way, cucumber is aware of detox and can manage the e2e tests
